# Property encryption configuration
jasypt:
  encryptor:
    password: ${ENCRYPT_MASTER_PASSWORD}

# Mailing configuration - SimpleJavaMail
# http://www.simplejavamail.org/#/configuration
simplejavamail:
  transportstrategy: SMTP_TLS
  smtp:
    host: smtp.gmail.com
    port: 587
    username: mevengar@gmail.com
    password: ${MAIL_PASSWORD}
  defaults:
    from: 
      name: Packt Notifier
      address: mevengar@gmail.com
    to:
      # Additional addresses can be added using semicolon (;)
      address: mevengar@gmail.com
   
    
# Service confguration
service:
  cron: 0 0 4 * * ?
  #base-urls:
   # web-shop: https://www.packtpub.com
   # web-subscription: https://subscription.packtpub.com
    #api-services: https://services.packtpub.com
    #api-static: https://static.packt-cdn.com
  #paths:
    #web-offers: /packt/offers/free-learning 
    #web-read: /
    #api-offers: /free-learning-v1/offers?dateFrom={0}&dateTo={1}
    #api-summary: /products/{0}/summary
  urls:
    web-offers: https://www.packtpub.com/packt/offers/free-learning
    web-read: https://subscription.packtpub.com/{0}
    #api-offers: https://services.packtpub.com/free-learning-v1/offers?dateFrom={0}&dateTo={1}
    #api-summary: https://static.packt-cdn.com/products/{0}/summary
  #proxy:
    # Do not add with 'http://' at the beginning!
    #host:
    #port:

endpoint:
  offers: https://services.packtpub.com/free-learning-v1/offers?dateFrom={0}&dateTo={1}
  summary: https://services.packtpub.com/free-learning-v1/offers?dateFrom={0}&dateTo={1}
     

