# General app configuration
app:
  lang: en
  notifications:
    twitter:
      enabled: true
      accessSecret: ${twitter.accessSecret}
      accessToken: ${twitter.accessToken}
      consumerKey:  ${twitter.consumerKey}
      consumerSecret: ${twitter.consumerSecret}
    email:
      enabled: true

service:
  cron: 0 0 4 * * ?
  
# Property encryption configuration
jasypt:
  encryptor:
    password: ${ENCRYPT_MASTER_PASSWORD}

# Mailing configuration - SimpleJavaMail
# http://www.simplejavamail.org/#/configuration
simplejavamail:
  transportstrategy: SMTP_TLS
  smtp:
    host: smtp.gmail.com
    port: 587
    username: mevengar@gmail.com
    password: ${MAIL_PASSWORD}
  defaults:
    from: 
      name: Packt Notifier
      address: mevengar@gmail.com
    to:
      # Additional addresses can be added using semicolon (;)
      address: mevengar@gmail.com

