%YAML 1.2
---

url:
  api:
    offers:  'https://services.packtpub.com/free-learning-v1/offers'
    summary: 'https://static.packt-cdn.com/products/{productId}/summary'
  web:
    shop: 'https://www.packtpub.com'
    free-learning: 'https://www.packtpub.com/packt/offers/free-learning'
    subscription: 'https://subscription.packtpub.com'

packt:
  hosts:
    services:
        host: 'https://services.packtpub.com'
        offers: '/free-learning-v1/offers'
        
        
# Property encryption configuration
jasypt:
  encryptor:
    password: ${ENCRYPT_MASTER_PASSWORD}

# Mailing configuration - SimpleJavaMail
# http://www.simplejavamail.org/#/configuration
simplejavamail:
  transportstrategy: SMTP_TLS
  smtp:
    host: smtp.gmail.com
    port: 587
    username: mevengar@gmail.com
    password: ${MAIL_PASSWORD}
  defaults:
    from: 
      name: Packt Notifier
      address: mevengar@gmail.com
    to:
      # Additional addresses can be added using semicolon (;)
      address: mevengar@gmail.com
   
    
# Service confguration
service:
  cron: 0 0 4 * * ?
  #cron: 0 * * * * * # For testing purposes
  #proxy:
    # Do not add with 'http://' at the beginning!
    #host:
    #port:
    

api-config:
  max-number-days: 3

