# Spring configuration
spring:  application:
    name: notifier-packt
    
# General app configuration
app:
  lang: en
  cron: 0 0 4 * * ?
  notifications:
    twitter:
      enabled: true
      accessSecret: ${twitter.accessSecret}
      accessToken: ${twitter.accessToken}
      consumerKey:  ${twitter.consumerKey}
      consumerSecret: ${twitter.consumerSecret}
    email:
      enabled: true

api:
  products: 
    name: products
    url: https://static.packt-cdn.com/products
  offers:
    name: offers
    url: https://services.packtpub.com/free-learning-v1/offers
  hashtags:
    name: hashtags
    url: https://api.ritekit.com/v1/stats/
    clientid: ${ritekit.clientId}

# Property encryption configuration
jasypt:
  encryptor:
    password: ${ENCRYPT_MASTER_PASSWORD}

# Mailing configuration - SimpleJavaMail
# http://www.simplejavamail.org/#/configuration
simplejavamail:
  transportstrategy: SMTP_TLS
  smtp:
    host: smtp.gmail.com
    port: 587
    username: mevengar@gmail.com
    password: ${MAIL_PASSWORD}
  defaults:
    from: 
      name: Packt Notifier
      address: mevengar@gmail.com
    to:
      # Additional addresses can be added using semicolon (;)
      address: mevengar@gmail.com

